### ISSUE TITLE
Missing Function After Pip Install

### ISSUE THREAD

**Issue by JamesInSATX** [devopsspiral/KubeLibrary#29]
After installing with 'pip install robotframework-kubelibrary', the 'get_deployments_in_namespace' function is missing from the KubeLibrary.py file. 

Using 'pip install robotframework-kubelibrary --upgrade' does not correct the problem. 

There is a workaround to copy the KubeLibrary.py file from this repository and manually paste into the installation.

**Comment by Nilsty** [comment]
Hi @JamesInSATX 
it's possible to directly reference a copy of the `KubeLibrary.py` in your robot-test suite like this:
`Library  ./KubeLibrary.py`

Other than that I'll try to make a new release to pip now.

**Comment by m-wcislo** [comment]
Will be handled by https://github.com/devopsspiral/KubeLibrary/pull/30

**Comment by Nilsty** [comment]
@JamesInSATX 
version 0.3.0 is now available on pypi https://pypi.org/project/robotframework-kubelibrary/0.3.0/#description
Including the 'get_deployments_in_namespace' keyword.
