### ISSUE TITLE
Unable to authenticatye to a K8s cluster

### ISSUE THREAD

**Issue by triceras** [devopsspiral/KubeLibrary#35]
Hi,

   I have been trying to use the KubeLibrary tool for testing my kubernetes clusters. However, as my kubeconfig file has multiplle clusters declared, but a single current context defined the tool is unable to read the current-context in the kubeconfig file and use it to establish connection to a cluster thus throwing the following SSL error:
```
[ WARN ] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get issuer certificate (_ssl.c:1123)'))': /k8s/clusters/local/api/v1/namespaces/cattle-system/pods?labelSelector=&watch=False
```

How can I establish connection if my kubeconfig has multiple clusters defined withing in ? Is there a way I could use a Bearer token to connect to K8s instead of using the kubeconfig file ?

Thanks !

**Comment by Nilsty** [comment]
Hi @triceras,
First of all thanks for your feedback. 
What I think works best is, if you isolate the kubeconfig you want to use into a separate file. You can isolate your current context with this line:
`kubectl config view --minify --flatten --context=$(kubectl config current-context) > my-kubeconfig.yaml`
Once you have that, you can pass that kubeconfig to the KubeLibrary when importing it.
`Library           KubeLibrary          /path/to/my-kubeconfig.yaml`

In regards to the bearer token: I think the python kubernetes client does not offer that option, Therefore it will be tricky to implement. I also think having a static bearer token to connect to your Kubernetes API endpoint is not the safest of things.

Two more things:
1. This blogpost gives a really good overview on handling kubeconfig files: https://ahmet.im/blog/mastering-kubeconfig/
2. Feel free to join us in the Robotframework Community Slack https://robotframework.org/#community
We have a channel there called #kubernetes

**Comment by triceras** [comment]
Hi Nils,

  In my opinion, isolating one kubeconfig file per cluster would add
unnecessary complexity if you want to test 50+ cluster. It would be easier
if your library could read a single kubeconfig and switch contexts as it
goes through the kubeconfig.

  Fortunately, the Kubernetes Python client offers the option of using a
bearer token to authenticate with a Kubernetes cluster. Here is a nice
example from stackoverflow
<https://stackoverflow.com/questions/48151388/kubernetes-python-client-authentication-issue>
giving a nice practical example, and here is one found in the official
Kubernetes Python client Github repository about the AuthorizationV1API
<https://github.com/kubernetes-client/python/blob/6d64cf67d38337a6fdde1908bdadf047b7118731/kubernetes/docs/AuthorizationV1Api.md>
giving another example on how to use it. I can also tell you that I am
passing in bearer tokens to the Kubernetes Python client for authentication
instead of using kubeconfig. I think allowing the use of a bearer token for
authentication would be a great feature to include in your tool.

 Thanks !

**Comment by m-wcislo** [comment]
Hi @triceras, this seems as a nice feature, not sure if we can handle in single PR. But we can start with context usage, give me some time to prepare PR.

For token authentication we are currently supporting incluster approach (https://github.com/kubernetes-client/python/blob/master/examples/in_cluster_config.py) as I understand this is not entirely what you expect but might be useful when you are running tests from within cluster.

**Comment by triceras** [comment]
Hi Michal,

  I can help you test thus feature in my environment.

Thanks !

**Comment by triceras** [comment]
I created a kubeconfig with a single cluster as per suggestion. The new kubeconfig file seems to be working as I can list any Kubernetes resources, but some test cases like the one for checking whether the pod log can be read are failing with a HTTP error 400 code being returned as shown below.
```
Logs of pod are available                                             | FAIL |
ApiException: (400)
Reason: Bad Request
HTTP response headers: HTTPHeaderDict({'Date': 'Wed, 17 Feb 2021 23:22:27 GMT', 'Content-Type': 'application/json', 'Content-Length': '233', 'Connection': 'keep-alive', 'Server': 'nginx/1.17.10', 'Audit-Id': '5ae36ba5-c8f0-4ca0-985d-237f94eab2c6'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"container rancher:0.0.2 is not valid for pod rancher-6f6c5c785b-2hzhw","reason":"BadRequest","code":400}
```
I can confirm that the container `rancher:0.0.2` belongs to the pod `_rancher-6f6c5c785b-2hzhw_`
```
# kubectl get pods -n cattle-system -o jsonpath="{..image}" | tr -s '[[:space:]]' '\n' | sort | uniq -c
   6 rancher:0.0.2
   8 rancher/rancher-agent:v2.4.4
```
is this error caused due to an authentication failure to the Kubernetes cluster ?

**Comment by m-wcislo** [comment]
It would be best to send the whole test report if possible, but from checking the test code we have hardcoded busybox container in the the test. See https://github.com/devopsspiral/KubeLibrary/blob/24f1e4518392b5697c9861986cc1bbca5de3a4a4/testcases/pod/pod_kw.robot#L103

To run the testcases we set some prerequisites in https://github.com/devopsspiral/KubeLibrary#other-tests. You would have to change the tests a little bit to test your own setup.

By the way I've created #36 PR which handles context and we would merge it soon. It will not be in Pypi package yet, but you could use following import to test it:
https://github.com/devopsspiral/KubeLibrary/blob/24f1e4518392b5697c9861986cc1bbca5de3a4a4/testcases/system_smoke_kw.robot#L9

**Comment by m-wcislo** [comment]
@triceras
#39 is ready to be tested, it allows now using bearer token as you described. Please check if that works for your case.
