### ISSUE TITLE
Add keywords to list cluster roles and cluster role bindings

### ISSUE THREAD

**Issue by Nilsty** [devopsspiral/KubeLibrary#42]
Keywords could be implemented based on the kubernetes client functions for 
[list_cluster_role](https://github.com/kubernetes-client/python/blob/master/kubernetes/docs/RbacAuthorizationV1Api.md#list_cluster_role)
and
[list_cluster_role_binding](https://github.com/kubernetes-client/python/blob/master/kubernetes/docs/RbacAuthorizationV1Api.md#list_cluster_role_binding)

**Comment by m-wcislo** [comment]
Solved by #58
